### PR TITLE
Conventional UI ported from FubuMVC

### PR DESCRIPTION
**Pull request by jbogard**
Had to take everything out related to Fubu pages etc.

There are still some things I don't quite get. There's an `ITagGenerator<T>` but I don't see any other closed type than `TagGenerator<ElementRequest>`. I'm also looking at removing so much configuration to wire dependencies etc. up:

```
SetServiceIfNone<IElementNamingConvention, DefaultElementNamingConvention>();

SetServiceIfNone(typeof(IElementGenerator<>), typeof(ElementGenerator<>));

SetServiceIfNone(typeof(ITagGenerator<>), typeof(TagGenerator<>));

AddService<ITagRequestActivator, ElementRequestActivator>();
AddService<ITagRequestActivator, ServiceLocatorTagRequestActivator>();

SetServiceIfNone<ITagGeneratorFactory, TagGeneratorFactory>();

SetServiceIfNone<ITemplateWriter, TemplateWriter>();

SetServiceIfNone<ITagRequestBuilder, TagRequestBuilder>();
```

That's what used to be in the FubuRegistry (now commented out). I'd like to see the need for all of this removed - today I do this in our MVC app w/ StructureMap registration. Very much trial-and-error to get it to work. There's an IServiceLocator in there now, which seems OK, but it's used internal to generating an element. 

I also removed template stuff, it was all tied to a specific kind of templating library. Not intended for this to get merged, but wanted to start the conversation.

### CODE REVIEW

**Comment by jeremydmiller** [comment]
"I don't see any other closed type than TagGenerator<ElementRequest>"

@jbogard I had grander plans once upon a time of extending the htmltag conventions to things like the <form> tag and maybe a couple other things. If we'd done that, there'd be TagGenerator<FormRequest> et al.

**Comment by jeremydmiller** [comment]
Ugh, that's going to be at least the 3rd copy of ReflectionHelper floating around (FubuCore & StructureMap). Guess it's just the way it's going to be. Wonder if we could get away with making that internal to prevent the conflicts?

**Comment by jeremydmiller** [comment]
@jbogard Let's definitely reevaluate the service location abstraction and how it's attached. I was never all that happy with the lifecycle of that anyway. It might be nice to get rid of the "Activator" concept too if that can be simplified.

Maybe go w/ that Func<Type, object> approach here for as simple as its usage is? It was definitely very useful to get at application services in html conventions though. Don't wanna lose that.

**Comment by jeremydmiller** [comment]
`AccessorRules` is something from FubuMVC.Core where you had a registry like thing to apply overrides on a property by property basis with an FI. Wasn't really fleshed out before the SPA tidal wave came. I had thoughts that it'd get extended to things like field level authorization, white/black listing, and validation. Only really used it for overriding Html conventions here.

**Comment by jbogard** [comment]
So...you know you can comment on individual files and changes, right?

**Comment by jbogard** [comment]
@jeremydmiller I think I'm close to a done state here. Got rid of the service locator, you now can just pass in a Func<Type, object>. An example of getting HtmlTag conventions into MVC is https://github.com/jbogard/ContosoUniversity/tree/master/src/ContosoUniversity (just converted the Department part).

**Comment by jbogard** [comment]
Do it live

**Pull request merged**
